### PR TITLE
Fix issue#3

### PR DESCRIPTION
**Pull request by joshbtn**
This fixes issue #3

### CODE REVIEW

**Comment by johanlunds** [comment]
Thanks!

**Comment by johanlunds** [comment]
I removed my package from Atom.io because I don't maintain it actively anymore (maybe again in the future). Are you fine to run it from Github directly or do you want me to push it again to Atom.io?

**Comment by joshbtn** [comment]
I'm fine with running it directly from github. Thanks!

**Comment by johanlunds** [comment]
Just happy to see it coming to some use. Send over more PRs and I will make sure to merge them.

**Comment by joshbtn** [comment]
Absolutely. Looks like you got off to a good start. Thanks for sharing!

**Pull request merged**
